superheroes/superheroes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superherosapp/', include('superheroesapp.urls')),
    path('', RedirectView.as_view(url='/superheroesapp/')),
]

superheroes/superheroesapp/urls.py
from . import views
from django.urls import path


app_name = 'superheroesapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:superhero_id>/', views.display_data, name='display_data'),
    path('new/', views.create_new_superhero, name='create_new_superhero'),
    path('edit/<int:superhero_id>/', views.superhero_edit, name='superhero_edit'),
    path('update/<int:superhero_id>/', views.update_superhero, name='update_superhero'),
    path('delete/<int:superhero_id>/', views.delete_superhero, name='delete_superhero')
]

superheroes/superheroesapp/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    superhero_name = models.CharField(max_length=50)
    alter_ego_name = models.CharField(max_length=50)
    primary_hero_ability = models.CharField(max_length=50)
    secondary_hero_ability = models.CharField(max_length=50)
    superhero_catchphrase = models.CharField(max_length=50)

    def __str__(self):
        return self.superhero_name

superheroes/superheroesapp/forms.py
from django import forms
from .models import Superhero


class superhero_forms(forms.ModelForm):
    class Meta:
        model = Superhero
        fields = '__all__'

superheroes/superheroesapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero
from .forms import superhero_forms

# Create your views here.


def create_new_superhero(request):
    if request.method == 'POST':
        superhero_name = request.POST.get('name')
        superhero_alter_ego = request.POST.get('alter_ego')
        superhero_primary_ability = request.POST.get('primary_superhero_ability')
        superhero_secondary_ability = request.POST.get('secondary_superhero_ability')
        superhero_catchphrase = request.POST.get('superhero_catchphrase')
        new_superhero = Superhero(superhero_name=superhero_name, alter_ego_name=superhero_alter_ego, primary_hero_ability=superhero_primary_ability, secondary_hero_ability=superhero_secondary_ability, superhero_catchphrase=superhero_catchphrase)
        new_superhero.save()

        return HttpResponseRedirect(reverse('superheroesapp:index'))
    else:
        return render(request, 'superheroesapp/index.html')


def index(request):

    all_superheroes = Superhero.objects.all()
    context = {
        'all_superheroes': all_superheroes
    }

    return render(request, 'superheroesapp/index.html', context)


def display_data(request, superhero_id):
    superhero_data = Superhero.objects.get(pk=superhero_id)
    context = {
        'superhero_data': superhero_data
    }
    return render(request, "superheroesapp/display.html", context)


def superhero_edit(request, superhero_id):
    superhero_edit_information = Superhero.objects.get(pk=superhero_id)
    context = {
        'superhero_update': superhero_edit_information
    }
    return render(request, "superheroesapp/edit.html", context)


def update_superhero(request, superhero_id):
    superhero_update = Superhero.objects.get(pk=superhero_id)
    form = superhero_forms(request.POST, instance=superhero_update)
    if form.is_valid():
        form.save()
        return redirect('/')
    context = {
        'form': form
    }
    return render(request, "superheroesapp/edit.html", context)


def delete_superhero(request, superhero_id):
    superhero_delete = Superhero.objects.get(pk=superhero_id)
    superhero_delete.delete()
    context = {
        'superhero_delete': superhero_delete
    }
    return redirect('/')

superheroes/superheroesapp/templates/superheroesapp/display.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title></title>
</head>
<body>
<center>
  <table class="table table-borderless table-sm fs-5">
      <thead>
    <tr>
      <th scope="col">Superhero Id</th>
      <th scope="col">Superhero Name</th>
      <th scope="col">AlterEgo Name</th>
      <th scope="col">Primary Hero Ability</th>
      <th scope="col">Secondary Hero Ability</th>
      <th scope="col">Catchphrase</th>
    </tr>
      </thead>
    <tr>
      <th scope="row">{{superhero_data.id}}</th>
      <td>{{superhero_data.superhero_name}}</td>
      <td>{{superhero_data.alter_ego_name}}</td>
      <td>{{superhero_data.primary_hero_ability}}</td>
      <td>{{superhero_data.secondary_hero_ability}}</td>
      <td>{{superhero_data.superhero_catchphrase}}</td>
      <td><a href="{% url 'superheroesapp:superhero_edit' superhero_data.id %}">Edit</a> </td>
      <td><a href="{%url 'superheroesapp:delete_superhero' superhero_data.id %}">Delete</a> </td>
    </tr>
  </table>



</center>
</body>
</html>

superheroes/superheroesapp/templates/superheroesapp/edit.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Edit Superhero Details</title>
</head>
<body>
    <center>
        <h1>Update Superhero information</h1>
        <form  action="{%url 'superheroesapp:update_superhero' superhero_update.id %}" method="post">
            {% csrf_token %}
        <table class="table table-borderless table-sm fs-4">
            <tr>
                <th scope="col">Superhero Id</th>
                <td scope="row"><input class="form-control" type="text" name="id" Value="{{superhero_update.id}}" readonly disabled></td>
            </tr>
            <tr>
                <th scope="col">Superhero Name</th>
                <td scope="row"><input class="form-control" type="text" name="superhero_name" Value="{{superhero_update.superhero_name}}"></td>
            </tr>
            <tr>
                <th scope="col">Superhero AlterEgo Name</th>
                <td scope="row"><input class="form-control" type="text" name="alter_ego_name" Value="{{superhero_update.alter_ego_name}}"></td>
            </tr>
            <tr>
                <th scope="col">Superhero Primary Ability</th>
                <td scope="row"><input class="form-control" type="text" name="primary_hero_ability" Value="{{superhero_update.primary_hero_ability}}"></td>
            </tr>
            <tr>
                <th scope="col">Superhero Secondary Ability</th>
                <td scope="row"><input class="form-control" type="text" name="secondary_hero_ability" Value="{{superhero_update.secondary_hero_ability}}"></td>
            </tr>
            <tr>
                <th scope="col">Superhero Catchphrase</th>
                <td scope="row"><input class="form-control" type="text" name="superhero_catchphrase" Value="{{superhero_update.superhero_catchphrase}}"></td>
            </tr>
        </table>
        <input class="form-control fs-2" type="submit" value="update"/>
        </form>
    </center>

</body>
</html>

superheroes/superheroesapp/templates/superheroesapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static  %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title></title>
</head>
<body>

<h1 class="fs-1">Superheroes</h1>
<ul class="list-group list-group-flush">
    {%for superhero in all_superheroes %}
    <li class="list-group-item"><h2> {{superhero.superhero_name}}: <a href="{% url 'superheroesapp:display_data' superhero.id %}">{{superhero.superhero_name}} details</a>  </h2></li>
    {% endfor %}
</ul>
    <form action="{%url 'superheroesapp:create_new_superhero' %}" method="post">
        {% csrf_token %}
        <input class="form-control" placeholder="name" type="text" name="name" id="name"><br>
        <input class="form-control" placeholder="alter ego name" type="text" name="alter_ego" id="alter_ego"><br>
       <input class="form-control" placeholder="primary superhero ability" type="text" name="primary_superhero_ability" id="primary_superhero_ability"><br>
        <input class="form-control" placeholder="secondary superhero ability" type="text" name="secondary_superhero_ability" id="secondary_superhero_ability"><br>
        <input class="form-control" placeholder="superhero catchphrase" type="text" name="superhero_catchphrase" id="superhero_catchphrase"><br>
        <input class="form-control fs-2" type="submit" value="Add new superhero.">
    </form>
<img src="{% static 'website/images/superheroes.png' %}" class="rounded mx-auto d-block">
</body>
</html>